version: '3'
services:
  db: 
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 81:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
